services:
  collector:
    build: .
    ports:
      - "7000:7000"
    volumes:
      - ./log/:/app/log/
    networks:
      - default

  cache:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - default

volumes:
  persitent: